services:
  adminer:
    image: adminer
    restart: always
    environment:
      - ADMINER_DESIGN=pappu687	
      - ADMINER_DEFAULT_SERVER=postgres
    depends_on:
      - postgres
    ports:
      - 8080:8080
    networks:
      - db

  postgres:
    image: postgis/postgis:16-master
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 30s
      timeout: 3s
      retries: 20
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/sql/01-init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./database/sql/02-extra.sql:/docker-entrypoint-initdb.d/02-extra.sql
    networks:
      - db

  back:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - ${API_PORT_EXTERNAL}:${API_PORT_INTERNAL}
    env_file:
      - ./.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - backend
      - db


  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  backend:
    driver: bridge
  db:
    driver: bridge

volumes:
  postgres-data:
