-- Adminer 4.8.1 PostgreSQL 16.3 (Debian 16.3-1.pgdg120+1) dump

DROP TABLE IF EXISTS "blocked_users";
CREATE TABLE "public"."blocked_users" (
    "id" integer NOT NULL,
    "blocker_id" integer NOT NULL,
    "blocked_id" integer NOT NULL,
    "blocked_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "blocked_users_pk" PRIMARY KEY ("id"),
    CONSTRAINT "blocked_users_pk_2" UNIQUE ("blocker_id", "blocked_id")
) WITH (oids = false);


DROP TABLE IF EXISTS "genders";
DROP SEQUENCE IF EXISTS gender_gender_id_seq;
CREATE SEQUENCE gender_gender_id_seq INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1;

CREATE TABLE "public"."genders" (
    "gender_id" integer DEFAULT nextval('gender_gender_id_seq') NOT NULL,
    "name_gender" character varying(100),
    CONSTRAINT "gender_name_gender_key" UNIQUE ("name_gender"),
    CONSTRAINT "gender_pkey" PRIMARY KEY ("gender_id")
) WITH (oids = false);

INSERT INTO "genders" ("gender_id", "name_gender") VALUES
(2,	'Woman'),
(3,	'Transgender'),
(4,	'Prefer not say'),
(1,	'Male');

DROP TABLE IF EXISTS "likes";
CREATE TABLE "public"."likes" (
    "like_id" integer NOT NULL,
    "user" integer NOT NULL,
    "user_liked" integer NOT NULL,
    CONSTRAINT "likes_pk" UNIQUE ("user_liked", "user"),
    CONSTRAINT "likes_pk_2" PRIMARY KEY ("like_id")
) WITH (oids = false);


DROP TABLE IF EXISTS "locations";
CREATE TABLE "public"."locations" (
    "location_id" integer NOT NULL,
    "latitude" numeric NOT NULL,
    "longitude" numeric NOT NULL,
    "city_name" character varying(100),
    CONSTRAINT "locations_pk" PRIMARY KEY ("location_id"),
    CONSTRAINT "locations_pk_2" UNIQUE ("longitude", "latitude")
) WITH (oids = false);


DROP TABLE IF EXISTS "matches";
CREATE TABLE "public"."matches" (
    "match_id" integer NOT NULL,
    "user_1" integer NOT NULL,
    "user_2" integer NOT NULL,
    "matched_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "matches_pk" UNIQUE ("user_1", "user_2"),
    CONSTRAINT "matches_pk_2" PRIMARY KEY ("match_id")
) WITH (oids = false);


DROP TABLE IF EXISTS "messages";
CREATE TABLE "public"."messages" (
    "message_id" integer NOT NULL,
    "content" character varying(500) NOT NULL,
    "created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "owner_user" integer NOT NULL,
    "target_user" integer NOT NULL,
    CONSTRAINT "messages_pk" PRIMARY KEY ("message_id")
) WITH (oids = false);


DROP TABLE IF EXISTS "notifications";
CREATE TABLE "public"."notifications" (
    "notification_id" integer NOT NULL,
    "title" character varying(60) NOT NULL,
    "type" integer NOT NULL,
    "target_user" integer NOT NULL,
    "has_read" boolean DEFAULT false NOT NULL,
    "notified_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "notifications_pk" PRIMARY KEY ("notification_id")
) WITH (oids = false);


DROP TABLE IF EXISTS "photos";
DROP SEQUENCE IF EXISTS picture_picture_id_seq;
CREATE SEQUENCE picture_picture_id_seq INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1;

CREATE TABLE "public"."photos" (
    "photo_id" integer DEFAULT nextval('picture_picture_id_seq') NOT NULL,
    "url" character varying(255) NOT NULL,
    "description" character varying(255),
    CONSTRAINT "picture_pkey" PRIMARY KEY ("photo_id"),
    CONSTRAINT "picture_url_key" UNIQUE ("url")
) WITH (oids = false);

INSERT INTO "photos" ("photo_id", "url", "description") VALUES
(1,	'https://assets/pictures/examples1.jpg',	'first picture ben');

DROP TABLE IF EXISTS "profile_photo";
DROP SEQUENCE IF EXISTS profile_picture_id_seq;
CREATE SEQUENCE profile_picture_id_seq INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1;

CREATE TABLE "public"."profile_photo" (
    "id" integer DEFAULT nextval('profile_picture_id_seq') NOT NULL,
    "profile_id" bigint NOT NULL,
    "photo_id" bigint NOT NULL,
    CONSTRAINT "profile_picture_pkey" PRIMARY KEY ("id")
) WITH (oids = false);


DROP TABLE IF EXISTS "profile_sexual_preferences";
CREATE TABLE "public"."profile_sexual_preferences" (
    "id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "profile_id" integer NOT NULL,
    "gender_id" integer NOT NULL,
    CONSTRAINT "profile_sexual-preference_pk_id" PRIMARY KEY ("id"),
    CONSTRAINT "profile_sexual-preference_pk_pair-gender-profile" UNIQUE ("gender_id", "profile_id")
) WITH (oids = false);

INSERT INTO "profile_sexual_preferences" ("id", "profile_id", "gender_id") VALUES
(4,	3,	1);

DROP TABLE IF EXISTS "profile_tag";
DROP SEQUENCE IF EXISTS profile_tag_id_seq;
CREATE SEQUENCE profile_tag_id_seq INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1;

CREATE TABLE "public"."profile_tag" (
    "id" integer DEFAULT nextval('profile_tag_id_seq') NOT NULL,
    "profile_id" bigint NOT NULL,
    "profile_tag" bigint NOT NULL,
    CONSTRAINT "profile_tag_pkey" PRIMARY KEY ("id")
) WITH (oids = false);


DROP TABLE IF EXISTS "profiles";
DROP SEQUENCE IF EXISTS profile_profile_id_seq;
CREATE SEQUENCE profile_profile_id_seq INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1;

CREATE TABLE "public"."profiles" (
    "profile_id" integer DEFAULT nextval('profile_profile_id_seq') NOT NULL,
    "onwer_user_id" bigint NOT NULL,
    "biography" character varying(1024) NOT NULL,
    "gender" integer NOT NULL,
    "age" integer,
    "main_picture" integer,
    "location" integer,
    "last_connection" timestamp,
    CONSTRAINT "profile_onwer_user_id_key" UNIQUE ("onwer_user_id"),
    CONSTRAINT "profile_pkey" PRIMARY KEY ("profile_id")
) WITH (oids = false);

COMMENT ON COLUMN "public"."profiles"."location" IS 'Contient les coordonnées GPS du quartier utilisateur';

INSERT INTO "profiles" ("profile_id", "onwer_user_id", "biography", "gender", "age", "main_picture", "location", "last_connection") VALUES
(3,	1,	'blab bla balb la',	1,	NULL,	NULL,	NULL,	NULL);

DROP TABLE IF EXISTS "sso_type";
CREATE TABLE "public"."sso_type" (
    "sso_id" integer NOT NULL,
    "name" character varying(50) NOT NULL,
    CONSTRAINT "sso_type_pk" PRIMARY KEY ("sso_id"),
    CONSTRAINT "sso_type_pk_2" UNIQUE ("name")
) WITH (oids = false);

COMMENT ON TABLE "public"."sso_type" IS 'stocker les differents type de SSO pris en charge (facebook + google ?)';


DROP TABLE IF EXISTS "tags";
DROP SEQUENCE IF EXISTS tag_tag_id_seq;
CREATE SEQUENCE tag_tag_id_seq INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1;

CREATE TABLE "public"."tags" (
    "tag_id" integer DEFAULT nextval('tag_tag_id_seq') NOT NULL,
    "tag_name" character varying(50) NOT NULL,
    CONSTRAINT "tag_pkey" PRIMARY KEY ("tag_id")
) WITH (oids = false);


DROP TABLE IF EXISTS "users";
DROP SEQUENCE IF EXISTS user_id_seq;
CREATE SEQUENCE user_id_seq INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1;

CREATE TABLE "public"."users" (
    "id" integer DEFAULT nextval('user_id_seq') NOT NULL,
    "username" character varying(50) NOT NULL,
    "last_name" character varying(255) NOT NULL,
    "first_name" character varying(255) NOT NULL,
    "email" character varying(255) NOT NULL,
    "password" character varying(255),
    "created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "sso_type" integer,
    CONSTRAINT "user_email_key" UNIQUE ("email"),
    CONSTRAINT "user_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "user_username_key" UNIQUE ("username")
) WITH (oids = false);

COMMENT ON COLUMN "public"."users"."sso_type" IS 'Si bonus authentification via facebook, google.. Si NOT_NULL pas de password, si NULL, il faut un password';

INSERT INTO "users" ("id", "username", "last_name", "first_name", "email", "password", "created_at", "sso_type") VALUES
(1,	'ben',	'DUCROCQ',	'Benjamin',	'bducrocq42@gmail.com',	'81dc9bdb52d04dc20036dbd8313ed055',	'2024-08-28 14:50:43.65664',	NULL);

DROP TABLE IF EXISTS "visited_profile_history";
CREATE TABLE "public"."visited_profile_history" (
    "id" integer NOT NULL,
    "visiter" integer NOT NULL,
    "visited" integer NOT NULL,
    CONSTRAINT "visited_profile_history_pk" UNIQUE ("visited", "visiter"),
    CONSTRAINT "visited_profile_history_pk_2" PRIMARY KEY ("id")
) WITH (oids = false);


ALTER TABLE ONLY "public"."blocked_users" ADD CONSTRAINT "blocked_users_users_id_fk" FOREIGN KEY (blocker_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE;
ALTER TABLE ONLY "public"."blocked_users" ADD CONSTRAINT "blocked_users_users_id_fk_2" FOREIGN KEY (blocked_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE;

ALTER TABLE ONLY "public"."likes" ADD CONSTRAINT "like_user_id_fk" FOREIGN KEY ("user") REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE;
ALTER TABLE ONLY "public"."likes" ADD CONSTRAINT "like_user_id_fk_2" FOREIGN KEY (user_liked) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE;

ALTER TABLE ONLY "public"."matches" ADD CONSTRAINT "matches_users_id_fk" FOREIGN KEY (user_1) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE;
ALTER TABLE ONLY "public"."matches" ADD CONSTRAINT "matches_users_id_fk_2" FOREIGN KEY (user_2) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE;

ALTER TABLE ONLY "public"."messages" ADD CONSTRAINT "messages_users_id_fk" FOREIGN KEY (owner_user) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE;
ALTER TABLE ONLY "public"."messages" ADD CONSTRAINT "messages_users_id_fk_2" FOREIGN KEY (target_user) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE;

ALTER TABLE ONLY "public"."notifications" ADD CONSTRAINT "notifications_users_id_fk" FOREIGN KEY (target_user) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE;

ALTER TABLE ONLY "public"."profile_photo" ADD CONSTRAINT "profile_picture_fk1" FOREIGN KEY (profile_id) REFERENCES profiles(profile_id) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."profile_photo" ADD CONSTRAINT "profile_picture_fk2" FOREIGN KEY (photo_id) REFERENCES photos(photo_id) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."profile_sexual_preferences" ADD CONSTRAINT "profile_sexual_preferences_gender_id_fkey" FOREIGN KEY (gender_id) REFERENCES genders(gender_id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE;
ALTER TABLE ONLY "public"."profile_sexual_preferences" ADD CONSTRAINT "profile_sexual_preferences_profile_profile_id_fk" FOREIGN KEY (profile_id) REFERENCES profiles(profile_id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE;

ALTER TABLE ONLY "public"."profile_tag" ADD CONSTRAINT "profile_tag_fk1" FOREIGN KEY (profile_id) REFERENCES profiles(profile_id) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."profile_tag" ADD CONSTRAINT "profile_tag_fk2" FOREIGN KEY (profile_tag) REFERENCES tags(tag_id) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."profiles" ADD CONSTRAINT "profile_gender_fkey" FOREIGN KEY (gender) REFERENCES genders(gender_id) ON UPDATE CASCADE ON DELETE RESTRICT NOT DEFERRABLE;
ALTER TABLE ONLY "public"."profiles" ADD CONSTRAINT "profile_onwer_user_id_fkey" FOREIGN KEY (onwer_user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE;
ALTER TABLE ONLY "public"."profiles" ADD CONSTRAINT "profile_photo_photo_id_fk" FOREIGN KEY (main_picture) REFERENCES photos(photo_id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE;
ALTER TABLE ONLY "public"."profiles" ADD CONSTRAINT "profiles_locations_location_id_fk" FOREIGN KEY (location) REFERENCES locations(location_id) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."users" ADD CONSTRAINT "users_sso_type_sso_id_fk" FOREIGN KEY (sso_type) REFERENCES sso_type(sso_id) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."visited_profile_history" ADD CONSTRAINT "visited_profile_history_user_id_fk" FOREIGN KEY (visited) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE;
ALTER TABLE ONLY "public"."visited_profile_history" ADD CONSTRAINT "visited_profile_history_user_id_fk_2" FOREIGN KEY (visiter) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE;

-- 2024-08-28 16:57:44.564816+00
