create table if not exists locations
(
    location_id integer generated by default as identity
        constraint locations_pk
            primary key,
    latitude    numeric not null,
    longitude   numeric not null,
    city_name   varchar(100)
        constraint locations_pk_3
            unique,
    constraint locations_pk_2
        unique (longitude, latitude)
);

