create table if not exists profile_sexual_preferences
(
    id         integer generated by default as identity
        constraint "profile_sexual-preference_pk_id"
            primary key,
    profile_id integer not null
        constraint profile_sexual_preferences_profile_profile_id_fk
            references profiles
            on update cascade on delete cascade,
    gender_id  integer not null
        references genders
            on update cascade on delete cascade,
    constraint "profile_sexual-preference_pk_pair-gender-profile"
        unique (gender_id, profile_id)
);

alter table profile_sexual_preferences
    owner to username42;

