create table if not exists fake_user_repoting
(
    id                integer generated by default as identity
        constraint fake_user_repoting_pk
            primary key,
    user_who_reported integer                             not null
        constraint fake_user_repoting_users_id_fk
            references users
            on update cascade on delete cascade,
    reported_user     integer                             not null
        constraint fake_user_repoting_users_id_fk_2
            references users
            on update cascade on delete cascade,
    reported_at       timestamp default CURRENT_TIMESTAMP not null,
    constraint fake_user_repoting_pk_2
        unique (user_who_reported, reported_user)
);

