create table if not exists gender
(
    gender_id   integer generated by default as identity
        constraint gender_pk
            primary key,
    name        varchar(60) not null,
    description varchar(60)
);

alter table gender
    owner to username42;

