create table if not exists picture
(
    picture_id       integer generated by default as identity
        constraint picture_pk
            primary key,
    url              varchar not null,
    description      integer,
    owner_profile_id integer not null
        constraint picture_profile_profile_id_fk
            references profile
            on update cascade on delete cascade
);

alter table picture
    owner to username42;

