create table if not exists "profile_sexual-preference"
(
    id         integer generated by default as identity
        constraint "profile_sexual-preference_pk_id"
            primary key,
    profile_id integer not null
        constraint "profile_sexual-preference_profile_profile_id_fk"
            references profile
            on update cascade on delete cascade,
    gender_id  integer not null
        constraint "profile_sexual-preference_gender_gender_id_fk"
            references gender
            on update cascade on delete cascade,
    constraint "profile_sexual-preference_pk_pair-gender-profile"
        unique (gender_id, profile_id)
);

alter table "profile_sexual-preference"
    owner to username42;

