create table if not exists "user"
(
    id         integer generated by default as identity
        constraint user_pk
            primary key,
    usermail   varchar(255) not null
        constraint user_pk_3
            unique,
    last_name  varchar(255) not null,
    first_name varchar(255),
    password   varchar(255) not null
);

alter table "user"
    owner to username42;

 "user"
    owner to username42;

